POST http://localhost:5000/notes
Content-Type: application/json

{
"longitude": "51.594720",
"latitude": "-0.155278",
"title": "Note here",
"category": "action",
"img_url": "https://cyclic-cyan-embarrassed-worm-eu-west-3.s3.eu-west-3.amazonaws.com/4ea9b7b8f3acc066c393dd246bb618ac",
"description": "This is description",
"user_email": "heloo@gmail.com"
}

###

GET http://localhost:5000/notes
Content-Type: application/json

###

GET http://localhost:5000/notes/3
Content-Type: application/json


###
DELETE http://localhost:5000/notes/15
Content-Type: application/json